2021-04-10 02:40:16:INFO:uvicorn.error: Started server process [3723]
2021-04-10 02:40:16:INFO:uvicorn.error: Waiting for application startup.
2021-04-10 02:40:16:INFO:uvicorn.error: Application startup complete.
2021-04-10 02:40:21:ERROR:uvicorn.error: Exception in ASGI application
Traceback (most recent call last):
  File "/home/hussain/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/hussain/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/hussain/.local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/hussain/.local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./api/endpoints/car.py", line 156, in read_item
    res = crud.get_car_filter_date(db, date_gt, limit=limit)
  File "./crud.py", line 148, in get_car_filter_date
    return db.query(CarDB).filter(*queries).limit(limit).all()
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column cars.car_page_link does not exist
LINE 1: ...rs.id AS cars_id, cars.car_name AS cars_car_name, cars.car_p...
                                                             ^

[SQL: SELECT cars.id AS cars_id, cars.car_name AS cars_car_name, cars.car_page_link AS cars_car_page_link, cars.body_style AS cars_body_style, cars.mileage AS cars_mileage, cars.exterior AS cars_exterior, cars.drivetrain AS cars_drivetrain, cars.transmission AS cars_transmission, cars.engine AS cars_engine, cars.city AS cars_city, cars.price AS cars_price, cars.vin AS cars_vin, cars.stock AS cars_stock, cars.website AS cars_website, cars.entry_date AS cars_entry_date, cars.img_link AS cars_img_link 
FROM cars 
 LIMIT %(param_1)s]
[parameters: {'param_1': 10}]
(Background on this error at: http://sqlalche.me/e/13/f405)
2021-04-10 02:40:49:INFO:uvicorn.error: Shutting down
2021-04-10 02:40:49:INFO:uvicorn.error: Waiting for application shutdown.
2021-04-10 02:40:49:INFO:uvicorn.error: Application shutdown complete.
2021-04-10 02:40:49:INFO:uvicorn.error: Finished server process [3723]
2021-04-10 02:43:18:INFO:uvicorn.error: Started server process [3905]
2021-04-10 02:43:18:INFO:uvicorn.error: Waiting for application startup.
2021-04-10 02:43:18:INFO:uvicorn.error: Application startup complete.
2021-04-10 02:43:18:INFO:uvicorn.error: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2021-04-10 02:43:28:ERROR:uvicorn.error: Exception in ASGI application
Traceback (most recent call last):
  File "/home/hussain/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/hussain/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/hussain/.local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/hussain/.local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/hussain/.local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./api/endpoints/car.py", line 156, in read_item
    res = crud.get_car_filter_date(db, date_gt, limit=limit)
  File "./crud.py", line 148, in get_car_filter_date
    return db.query(CarDB).filter(*queries).limit(limit).all()
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/hussain/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column cars.car_page_link does not exist
LINE 1: ...rs.id AS cars_id, cars.car_name AS cars_car_name, cars.car_p...
                                                             ^

[SQL: SELECT cars.id AS cars_id, cars.car_name AS cars_car_name, cars.car_page_link AS cars_car_page_link, cars.body_style AS cars_body_style, cars.mileage AS cars_mileage, cars.exterior AS cars_exterior, cars.drivetrain AS cars_drivetrain, cars.transmission AS cars_transmission, cars.engine AS cars_engine, cars.city AS cars_city, cars.price AS cars_price, cars.vin AS cars_vin, cars.stock AS cars_stock, cars.website AS cars_website, cars.entry_date AS cars_entry_date, cars.img_link AS cars_img_link 
FROM cars 
 LIMIT %(param_1)s]
[parameters: {'param_1': 10}]
(Background on this error at: http://sqlalche.me/e/13/f405)
2021-04-10 02:45:26:INFO:uvicorn.error: Shutting down
2021-04-10 02:45:26:INFO:uvicorn.error: Waiting for application shutdown.
2021-04-10 02:45:26:INFO:uvicorn.error: Application shutdown complete.
2021-04-10 02:45:26:INFO:uvicorn.error: Finished server process [3905]
